### ISSUE TITLE
Specify Nuitka version as an input parameter to the Action 

### ISSUE THREAD

**Issue by jimkring** [Nuitka/Nuitka-Action#5]
Users may want to specify the version of nuitka to use for the build. As such, it could be good to allow passing in the nuitka version as an input parameter to the action.

**Comment by kayhayen** [comment]
Maybe that means, one can use the pip installable URL types?

**Comment by jimkring** [comment]
@kayhayen  
  
Yes, my thinking was that a user could specify a \``nuitka-version`\` version like this:

### Semantic Version

```
- Name: My App Build
  uses: Nuitka/Nuitka-Action@v0.5
  with:
    nuitka-version: 1.0
    script-name: my_app.py
    standalone: true
```

### Version URLs

We could (as you suggested) detect a url and have pip install from the url, too. 

```
- Name: My App Build
  uses: Nuitka/Nuitka-Action@v0.5
  with:
    nuitka-version: https://github.com/Nuitka/Nuitka/archive/factory.zip
    script-name: my_app.py
    standalone: true
```

### Special Version Keywords

We could also support some keywords like `factory`.

```
- Name: My App Build
  uses: Nuitka/Nuitka-Action@v0.5
  with:
    nuitka-version: factory
    script-name: my_app.py
    standalone: true
```

### Git Tags/SHA Refs with "@"

We could also detect an `@` symbol before the version and treat that as a git tag/sha (e.g. `@hotfix/0.9.6`) that expands (for pip install) to this  `git+ssh://git@github.com:Nuitka/Nuitka.git@hotfix/0.9.6#egg=nuitka`:

```
- Name: My App Build
  uses: Nuitka/Nuitka-Action@v0.5
  with:
    nuitka-version: @hotfix/0.9.6
    script-name: my_app.py
    standalone: true
```
