### ISSUE TITLE
File that definitely exists in working directory is not found

### ISSUE THREAD

**Issue by axQuadratic** [Nuitka/Nuitka-Action#52]
Not sure if this is the place for general support, but I really am at my wit's end here and do not see a better option. I am attempting to use this action in my repo to build an executable from a file in the repo's top level, `main.py`. Below is the yaml for the step in question:
```
- name: Build executable
  uses: Nuitka/Nuitka-Action@v1.1
  with:
    script-name: main.py
    standalone: true
    enable-console: true
    enable-plugins: tk-inter
```
The usage guide on this repo seems to suggest this is the way to go for what I'm trying to do, however, no matter what I try, I always receive the same error:
`FATAL: Error, file 'main.py' is not found.`
I have tried explicitly setting `working-directory: .`, but it does not make any difference. What am I doing wrong?
