### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified

### ISSUE THREAD

**Issue by xhatt** [Nuitka/Nuitka-Action#54]
```
name: Python Package on Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on:  windows-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Version range or exact version of a Python version to use, using SemVer's version range syntax

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry 
          poetry install

      - name: Build package
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
          enable-plugins: tk-inter
          include-data-files: | 
            ./dll/*.dll=dll/ 
            logo.ico=logo.ico
          windows-icon-from-ico: logo.ico
          output-file: test.exe
          windows-console-mode: disable

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: twitter_bot
          path: |
            build/*.exe
```

Nuitka-Options: Used command line options: --onefile --include-data-files="./dll/*.dll=dll/ " --include-data-files=logo.ico=logo.ico --windows-icon-from-ico=logo.ico --output-file=\u63a8\u7279\u52a9\u624b.exe --disable-console --assume-yes-for-downloads --output-dir=build --script-name=main.py --enable-plugins=tk-inter
Nuitka:WARNING: The old console option '--disable-console' should not be given anymore, use '--windows-console-mode=disable' instead. It also has the extra mode 'attach' to consider.
Nuitka: Starting Python compilation with Nuitka '2.3.5' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 84 files (no progress information available for this stage).
Nuitka-Scons: Compiled 84 C files using clcache with 0 个缓存 hits and 84 个缓存 misses.
Nuitka-Postprocessing: Adding 1 icon(s) from icon file 'logo.ico'.
Nuitka: Downloading 'https://dependencywalker.com/depends22_x64.zip'.
Nuitka: Extracting to 'D:\a\_actions\Nuitka\Nuitka-Action\main\nuitka\cache\downloads\depends\x86_64\depends.exe'
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\nuitka\__main__.py", line 161, in <module>
    main()
  File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\nuitka\__main__.py", line 147, in main
    MainControl.main()
  File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\nuitka\MainControl.py", line 1130, in main
    _main()
  File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\nuitka\MainControl.py", line 1036, in _main
    copyDataFiles(standalone_entry_points=getStandaloneEntryPoints())
  File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\nuitka\freezer\IncludedDataFiles.py", line 617, in copyDataFiles
    _handleDataFile(
  File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\nuitka\freezer\IncludedDataFiles.py", line 581, in _handleDataFile
    copyFileWithPermissions(
  File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages\nuitka\utils\FileOperations.py", line 1000, in copyFileWithPermissions
    shutil.copy2(
  File "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\shutil.py", line 460, in copy2
    _winapi.CopyFile2(src_, dst_, flags)
FileNotFoundError: [WinError 3] The system cannot find the path specified
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.
Error: Process completed with exit code 1.
