### ISSUE TITLE
Images from directories added using include-data-dir are not recognized by compiled executable

### ISSUE THREAD

**Issue by Shararamosh** [Nuitka/Nuitka-Action#65]
I'm trying to add folder with images to my onefile Nuitka Windows executable using the following workflow step:
```
- name: Run Nuitka for Deserializer
  uses: Nuitka/Nuitka-Action@main
  with:
      nuitka-version: main
      script-name: flatc_deserializer.py
      onefile: true
      enable-plugins: tk-inter
      include-data-dir: |
        .\localization=localization
        .\images=images
      windows-icon-from-ico: "images/flatbuffers-logo-clean.png"
```
![image](https://github.com/user-attachments/assets/68e46ecb-11c2-4b18-aef5-2dcc7cdec3ec)
However when I try launching resulting executable, it throws "FileNotFoundError" when image file from included folder is referenced.
![image](https://github.com/user-attachments/assets/c06b058e-3e0b-4fc0-bba1-00bc28b09930)
It tries to find this image in Downloads/images folder, but fails. I want to know how I can fix that.
