### ISSUE TITLE
Nuitka-Action does not work with uv when using PySide6 and uv

### ISSUE THREAD

**Issue by kowyo** [Nuitka/Nuitka-Action#70]
My action file:

```
    uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: app/main.py
        mode: standalone
        enable-plugins: pyside6
        include-data-dir: app=app
        include-data-files: .app-version=.app-version
        macos-target-arch: ${{ matrix.target_arch }}
        macos-app-icon: app/resources/icons/icon.icns
        macos-app-name: "HITSZ Connect Verge"
        output-dir: dist
```

It reported error in action:

https://github.com/kowyo/hitsz-connect-verge/actions/runs/13858770128/job/38781684061#step:7:225
